In [2]:
import numpy as np
# Properties

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr.shape)   # dimensions = m x n
print(arr.size)    # total elements = 9
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [ ]:
(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64