In [1]:
import numpy as np
# Slicing

arr = np.array([1, 2, 3, 4, 5])

print(arr[1:4])   # [start, end, step]
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [ ]:
[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]