In [1]:
import numpy as np

# Boolean Indexing

arr = np.array([1, 2, 3, 4, 5])

print(arr[arr > 2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

[3 4 5]
[2 4]
[1 3 5]


In [ ]:
[3 4 5]
[2 4]
[1 3 5]